### PR TITLE
Update references to Freenode to Libera

### PR DESCRIPTION
**Pull request by fredster33**
See also https://phabricator.wikimedia.org/T283273 and https://meta.wikimedia.org/w/index.php?diff=21476411&diffmode=source

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Is there actually a semantic-mediawiki channel on there with anyone in it?

**Comment by JeroenDeDauw** [comment]
The new chat might be better to link https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki_chatroom

**Comment by fredster33** [comment]
Last time I checked there seemed to be people on IRC. I can open a new PR adding the Matrix/Telegram link as well, that would probably be helpful too.

**Comment by fredster33** [comment]
There's also a bunch of other repos under this org that use the same sentence. I'd be happy to open PRs and clean up all of them.

**Pull request merged**
